### ISSUE TITLE
【催更】新的穆译什么时候发布？

### ISSUE THREAD

**Issue by 775405984** [greatghoul/smooth-translator#4]
不会等到明年吧？

催更可耻，我先逃...

**Comment by greatghoul** [comment]
https://chrome.google.com/webstore/detail/%E7%A9%86%E8%AF%91/mcfdomppancgaladcgflcgahbgcgbagb?hl=en

发现了，截图什么的都还没有做，商量也正在审核中，大概需要过上一会儿才能用。

**Comment by greatghoul** [comment]
稍后有闲时间了再补图。
