### ISSUE TITLE
【数据源】速度比TransIt慢

### ISSUE THREAD

**Issue by 775405984** [greatghoul/smooth-translator#5]
穆译的翻译API是哪家的？加载好慢，比TransIt慢多了。

**Comment by greatghoul** [comment]
还是有道的，默认走 web 页面抓取，按理不应该存在速度上的差异。我做下对比。

**Comment by greatghoul** [comment]
transit 也是走的同样的通道。

**Comment by shangmaumau** [comment]
必应的翻译比有道的强多了。必应会提供最新的网络上的一些翻译结果，在未收入规范的词典之前，都可以查看得到。而且必应提供的翻译结果，也丰富得多。强烈建议开发者使用必应为默认。

**Comment by greatghoul** [comment]
在这个扩展中，我选择有道是有原因的，有道有 API 可以用，虽然我默认使用的抓取页面的方式，但一旦页面变化，我可以选择 fallback 到 API。

如果你比较喜欢必应翻译，可以使用之前的扩展（只修 bug，不再有功能更新）或者另一个更新非常活跃的扩展 https://github.com/Selection-Translator/crx-selection-translate

@shangleixun

**Comment by greatghoul** [comment]
https://github.com/GDG-Xian/crx-transit/issues/78

我看到你在这里也提了个 Issue，我已经更新了，你可以试一下。

@shangleixun

**Comment by greatghoul** [comment]
我不知道是不是你网络的问题，我在我在机器上没有感觉怎么慢呀。
![image](https://user-images.githubusercontent.com/208966/34167030-87d9703a-e51b-11e7-8d9b-29ffe3935b13.png)

@775405984

**Comment by 775405984** [comment]
@greatghoul 有可能，现在又奇迹般地好了

**Comment by greatghoul** [comment]
@775405984 

我现在遇到个非常尴尬的问题，开着 ExpressVPN，有道的 API 就不能访问了，翻译结果完全弹不出来了。这个 VPN 简直让人又爱又恨。

所以有时候慢，也有可能是使用的代理的问题。如果没有挂代理，即使慢，也不应该慢得太离谱，有道不至于在这方面没有优化，毕竟国内的服务。

**Comment by 775405984** [comment]
@greatghoul 
我用Proxy SwitchyOmega管理代理，国内的服务器都是直连，没用VPN全局，所以应该不会出现你说的情况。

话说，你的 ExpressVPN 买的什么套餐？速度咋样？

**Comment by greatghoul** [comment]
@775405984 一个月9刀左右，速度一般，但比较稳定，十九大期间都能用。

**Comment by 775405984** [comment]
@greatghoul  据说2018年02月初开始所有的个人VPN都不能使用了。https://www.bloomberg.com/news/articles/2017-07-10/china-is-said-to-order-carriers-to-bar-personal-vpns-by-february

**Comment by greatghoul** [comment]
个人 VPN 是怎么定义的？
