### ISSUE TITLE
【兼容性】貌似与Transit有点冲突

### ISSUE THREAD

**Issue by 775405984** [greatghoul/smooth-translator#6]
由于接口没有多选项，有道不全，必应高冷，我就两个扩展一起搭配着用，发现弹出的信息框都在右上角，而且是覆盖的，不知道算不算BUG？

**Comment by greatghoul** [comment]
这个我也想不出什么特别好的解决方法，看来你得禁用其中一个。

**Comment by 775405984** [comment]
@greatghoul 

你可以增加多选接口选项，划词可以多家翻译

**Comment by greatghoul** [comment]
我单开这个扩展其实的目的之一就是减少接口选项。

transit 是支持多家翻译的，但 smooth 刻意去掉了。

https://github.com/Selection-Translator/crx-selection-translate
这个扩展也支持多个翻译服务。
